<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VR92I9TB" failures="4" tests="12" name="PetTests" time="21.763" errors="0" timestamp="2023-06-17T22:16:10 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.741"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.472"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="3.052"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.535"/>
  <testcase classname="api.test.UserTests2" name="testPostUser" time="1.498"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.533"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.891"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.502"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NullPointerException: Cannot invoke &amp;quot;org.apache.poi.xssf.usermodel.XSSFRow.getLastCellNum()&amp;quot; because &amp;quot;this.row&amp;quot; is null">
      <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFRow.getLastCellNum()" because "this.row" is null
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFRow.getLastCellNum()" because "this.row" is null
at api.utilities.XLUtility.getCellCount(XLUtility.java:51)
at api.utilities.DataProviders.getAllData(DataProviders.java:16)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.473">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.316">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.532">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUserByName(DDTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- PetTests -->
